AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DocumentConversionJobsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "DocumentConversionJobs"
      AttributeDefinitions:
        - AttributeName: "job_id"
          AttributeType: "S"  # String type for Partition Key
        - AttributeName: "created_at"
          AttributeType: "S"  # String type for Sort Key
      KeySchema:
        - AttributeName: "job_id"
          KeyType: "HASH"  # Partition Key
        - AttributeName: "created_at"
          KeyType: "RANGE"  # Sort Key
      BillingMode: "PAY_PER_REQUEST"  # On-demand billing mode
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Project"
          Value: "DocumentConversion"

Outputs:
  TableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref DocumentConversionJobsTable
    Export:
      Name: "DocumentConversionJobsTableName"
